stages:
  - deploy

deploy_uptime_kuma:
  stage: deploy
  tags:
    - irlanda-prod
  before_script:
    # Garante que o Runner use o contexto do Docker Rootless
    - export PATH=$PATH:$HOME/bin
    - export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
  script:
    - echo "Iniciando o build..."
    - docker build --target release -t uptime-kuma-custom -f docker/dockerfile .
    - echo "Limpando containers antigos..."
    - docker stop uptime-kuma || true
    - docker rm uptime-kuma || true
    - echo "Subindo a nova versão customizada..."
    - |
      docker run -d \
        --name uptime-kuma \
        --restart always \
        -p 3001:3001 \
        -v /opt/uptimekuma/data:/app/data \
        uptime-kuma-custom
    - echo "Deploy realizado com sucesso!"
  only:
    - tjpi
